language: cpp
compiler:
    - clang
    - gcc
os:
    - linux
    - osx
before_install:
    # Config 
    - $CC --version
    - $CXX --version
    - cmake --version
    - lcov --version
    - gcov --version
    # Build GTest
    - pushd "`pwd`"
    - sudo mkdir /usr/src/gtest/build
    - cd /usr/src/gtest/build
    - sudo cmake .. -DBUILD_SHARED_LIBS=1
    - sudo make -j 4
    - sudo ln -s /usr/src/gtest/build/libgtest.so /usr/lib/libgtest.so
    - sudo ln -s /usr/src/gtest/build/libgtest_main.so /usr/lib/libgtest_main.so
    - popd

before_script:
    - mkdir build && cd build

script:
    - cmake ..
    - make VERBOSE=1
