language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - cmake
      - lcov
      - libgtest-dev
      - google-mock

before_script:
    # Config 
    - $CC --version
    - $CXX --version
    - cmake --version
    - gcov --version
    - lcov --version

before_install:
  # Install OS X stuff
  - |
    if test "$TRAVIS_OS_NAME" == "osx"; then
        brew update
        brew install lcov
    fi

install:
    # Build GTest and GMock
    - pushd "`pwd`"
    - cd /usr/src/gtest && sudo cmake -DBUILD_SHARED_LIBS=ON . && sudo make -j 4 && sudo cp libg* /usr/local/lib/; cd -
    - cd /usr/src/gmock && sudo cmake -DBUILD_SHARED_LIBS=ON . && sudo make -j 4 && sudo cp libg* /usr/local/lib/; cd -
    - export GTEST_ROOT=/usr/src/gtest/
    - export GMOCK_ROOT=/usr/src/gtest/
    - sudo ldconfig
    - popd

script:
    # Link this
    - npm link
    - npm install -g yo
    # Launch yo cpp-suite
    - mkdir testbuild && cd testbuild
    - "echo 'yeotest\nyeotest\nYeotest\nme\ny\n' | yo cpp-suite"
    - "echo 'MyClass\n\n\ny\n' | yo cpp-suite:addclass"
    # Build dummy project
    - mkdir build && cd build
    - cmake ..
    - make VERBOSE=1
